name: 機能追加・改善
description: 新機能の提案や既存機能の改善案
title: "[Feature] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 機能追加・改善提案
        新しい機能や既存機能の改善についてご提案ください。

  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: 提案する機能や改善の概要を簡潔に説明してください
      placeholder: "例: ゴールに期限を設定できる機能"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: 目的・背景
      description: なぜこの機能が必要なのか、どのような課題を解決するのかを説明してください
      placeholder: "現在はゴールに期限がないため、スケジュール管理が困難"
    validations:
      required: true

  - type: textarea
    id: detailed-description
    attributes:
      label: 詳細
      description: 機能の詳細な仕様や動作について説明してください
      value: |
        ### 実装したい機能
        
        ### ユーザーへの影響
        
        ### 技術的考慮事項
        
      placeholder: "具体的な画面設計、操作フロー、技術的な実装方法など"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の優先度を選択してください
      options:
        - 高（緊急に必要）
        - 中（重要だが急がない）
        - 低（あると便利）
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: 対象ユーザー
      description: この機能の主な対象となるユーザーを選択してください
      options:
        - すべてのユーザー
        - 新規ユーザー
        - 既存ユーザー
        - 管理者
        - その他
      multiple: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えられる実装方法や解決策があれば記載してください
      placeholder: "別のアプローチや類似機能の例など"

  - type: textarea
    id: related
    attributes:
      label: 関連
      description: 関連するIssue、PR、ドキュメントなどがあれば記載してください
      placeholder: "関連するストーリー、タスク、リンク等"
